version: "3"

services:
  frontend:
    build: ./frontend
    hostname: frontend
    ports:
      - "80:80"
    restart: always
  
  api:
    depends_on:
      - frontend
    build: .
    container_name: 3DSSL-api
    environment:
      - NVIDIA_VISIBLE_DEVICES=3 # which gpu do you want to use for this 

    restart: always